const mongoose = require("mongoose");


/* =========================================================
   FINORA REFERRAL COMMISSION MODEL

   COMMISSION IS GENERATED ONLY FROM A USER'S
   FIRST APPROVED DEPOSIT.

   LEVEL 1 = 15%
   LEVEL 2 = 5%
   LEVEL 3 = 2%
========================================================= */


const referralCommissionSchema = new mongoose.Schema(
    {

        /* =================================================
           USER WHO RECEIVES THE COMMISSION
        ================================================= */

        recipient: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
            index: true
        },


        /* =================================================
           USER WHO MADE THE DEPOSIT
        ================================================= */

        referredUser: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
            index: true
        },


        /* =================================================
           DEPOSIT THAT GENERATED THIS COMMISSION
        ================================================= */

        deposit: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Deposit",
            required: true,
            index: true
        },


        /* =================================================
           REFERRAL LEVEL

           1 = DIRECT REFERRAL
           2 = SECOND LEVEL
           3 = THIRD LEVEL
        ================================================= */

        level: {
            type: Number,
            enum: [
                1,
                2,
                3
            ],
            required: true
        },


        /* =================================================
           COMMISSION RATE

           Stored as percentage:
           15 = 15%
           5  = 5%
           2  = 2%
        ================================================= */

        rate: {
            type: Number,
            enum: [
                15,
                5,
                2
            ],
            required: true
        },


        /* =================================================
           DEPOSIT AMOUNT USED FOR CALCULATION
        ================================================= */

        depositAmount: {
            type: Number,
            required: true,
            min: 10000
        },


        /* =================================================
           COMMISSION AMOUNT
        ================================================= */

        amount: {
            type: Number,
            required: true,
            min: 0
        },


        /* =================================================
           PROCESSING STATUS
        ================================================= */

        status: {
            type: String,
            enum: [
                "credited",
                "reversed"
            ],
            default: "credited",
            index: true
        },


        /* =================================================
           WALLET CREDIT TIMESTAMP
        ================================================= */

        creditedAt: {
            type: Date,
            default: Date.now
        }

    },


    {
        timestamps: true
    }
);


/* =========================================================
   INDEXES
========================================================= */


/*
   Quickly load commissions received by a user.
*/

referralCommissionSchema.index({
    recipient: 1,
    createdAt: -1
});


/*
   Quickly load commissions generated by a referred user.
*/

referralCommissionSchema.index({
    referredUser: 1,
    createdAt: -1
});


/*
   IMPORTANT DUPLICATE-PROTECTION INDEX.

   The same recipient cannot receive the same referral
   commission twice from the same deposit at the same level.
*/

referralCommissionSchema.index(
    {
        deposit: 1,
        recipient: 1,
        level: 1
    },
    {
        unique: true
    }
);


/* =========================================================
   EXPORT
========================================================= */

module.exports =
    mongoose.model(
        "ReferralCommission",
        referralCommissionSchema
    );
